### ISSUE TITLE
TypeError: Cannot read property 'child' of undefined

### ISSUE THREAD

**Issue by eush77** [stormslowly/makefileVisualization#3]
Using makev@0.0.5:

```
makev/lib/depBuilder.js:36
      deps[currentTarget].child.upush({
                         ^
TypeError: Cannot read property 'child' of undefined
    at Stream.<anonymous> (makev/lib/depBuilder.js:36:26)
    at Stream.stream.write (makev/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:32:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:166:7)
    at drain (makev/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (makev/node_modules/through/index.js:45:5)
    at Stream.write (makev/lib/filterDepline.js:15:12)
    at Stream.stream.write (makev/node_modules/through/index.js:26:11)
    at LineStream.ondata (_stream_readable.js:524:20)
```

```
$ node --version
v1.6.2
```

**Comment by stormslowly** [comment]
very strange node version 
office version is 0.xx.xx but you are in 1.xx.xx

**Comment by eush77** [comment]
This issue reproduces on 0.10 and 0.12 as well. Node version doesn't seem to be relevant. (And 1.xx.xx are [iojs](https://iojs.org) versions btw.)

If it helps, I'm trying to apply makev to [one of](http://git.io/vIDfE) [Spidermonkey](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Build_Documentation)'s makefiles.
